"""Write store/seed.sql: 3 airports, 200 flights, existing reservations."""

from __future__ import annotations

import random
from pathlib import Path

STORE_DIR = Path(__file__).resolve().parent
SEED_PATH = STORE_DIR / "seed.sql"

AIRPORTS = (
    ("SFO", "San Francisco"),
    ("JFK", "New York"),
    ("LAX", "Los Angeles"),
)

# Original task catalog — gold UA100 must stay bookable for Alice Chen.
REQUIRED_FLIGHTS = (
    ("UA100", "SFO", "JFK", "2026-10-15", "08:15", "morning", 349, 5),
    ("B6200", "SFO", "JFK", "2026-10-15", "07:50", "morning", 499, 4),
    ("UA900", "SFO", "JFK", "2026-10-15", "19:40", "evening", 199, 6),
    ("UA150", "SFO", "JFK", "2026-10-15", "09:05", "morning", 401, 4),
    ("DL220", "SFO", "JFK", "2026-10-15", "11:55", "morning", 379, 3),
    ("UA101", "SFO", "JFK", "2026-10-16", "08:00", "morning", 329, 5),
    ("UA300", "SFO", "LAX", "2026-10-15", "07:30", "morning", 199, 8),
)

DATES = (
    "2026-10-14",
    "2026-10-15",
    "2026-10-16",
    "2026-10-17",
    "2026-10-18",
)
DEPARTURES = (
    ("06:10", "morning"),
    ("07:15", "morning"),
    ("08:15", "morning"),
    ("09:40", "morning"),
    ("11:20", "morning"),
    ("17:05", "evening"),
    ("18:30", "evening"),
    ("19:40", "evening"),
    ("21:15", "evening"),
)
CARRIERS = ("UA", "DL", "AA", "B6")
PASSENGERS = (
    "Bob Lee",
    "Priya Shah",
    "Marco Rossi",
    "Nina Patel",
    "James Okonkwo",
    "Sofia Alvarez",
    "Kenji Mori",
    "Elena Popov",
    "Chris Walsh",
    "Amara Diallo",
    "Noah Berg",
    "Yuki Tanaka",
    "Hannah Cole",
    "Omar Haddad",
    "Lila Nguyen",
    "Peter Novak",
    "Rita Gomez",
    "Sam Irons",
    "Tina Brooks",
    "Victor Chen",
    "Wendy Park",
    "Xavier Diaz",
    "Yara Singh",
    "Zane Cooper",
    "Owen Blake",
)
TARGET_FLIGHTS = 200
TARGET_RESERVATIONS = 25
PROTECTED_IDS = {"UA100"}


def sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def build_flights(rng: random.Random) -> list[tuple]:
    flights = [tuple(row) for row in REQUIRED_FLIGHTS]
    taken_ids = {row[0] for row in flights}
    taken_slots = {(row[1], row[2], row[3], row[4]) for row in flights}
    codes = [code for code, _ in AIRPORTS]
    routes = [(a, b) for a in codes for b in codes if a != b]
    serial = 1000
    while len(flights) < TARGET_FLIGHTS:
        origin, dest = rng.choice(routes)
        date = rng.choice(DATES)
        depart, tod = rng.choice(DEPARTURES)
        slot = (origin, dest, date, depart)
        if slot in taken_slots:
            serial += 1
            continue
        carrier = rng.choice(CARRIERS)
        flight_id = f"{carrier}{serial}"
        serial += 1
        if flight_id in taken_ids:
            continue
        taken_ids.add(flight_id)
        taken_slots.add(slot)
        price = rng.choice((179, 199, 229, 259, 289, 319, 349, 379, 401, 449, 499, 559))
        seats = rng.randint(2, 8)
        flights.append((flight_id, origin, dest, date, depart, tod, price, seats))
    return flights


def build_reservations(
    rng: random.Random, flights: list[list],
) -> list[tuple[str, str]]:
    candidates = [row for row in flights if row[0] not in PROTECTED_IDS and row[7] > 0]
    rng.shuffle(candidates)
    reservations: list[tuple[str, str]] = []
    sold = next((row for row in candidates if 2 <= row[7] <= 4), candidates[0])
    for i in range(sold[7]):
        reservations.append((sold[0], f"Standby {i + 1}"))
        sold[7] -= 1
    others = [row for row in candidates if row[0] != sold[0] and row[7] > 1]
    for i, row in enumerate(others):
        if len(reservations) >= TARGET_RESERVATIONS:
            break
        reservations.append((row[0], PASSENGERS[i % len(PASSENGERS)]))
        row[7] -= 1
    return reservations


def render_sql(flights: list[tuple], reservations: list[tuple[str, str]]) -> str:
    lines = [
        "-- Generated by store/generate_seed.py. Do not edit by hand.",
        "INSERT INTO airports (code, city) VALUES",
    ]
    airport_rows = [f"  ({sql_str(code)}, {sql_str(city)})" for code, city in AIRPORTS]
    lines.append(",\n".join(airport_rows) + ";")
    lines.append("")
    lines.append(
        "INSERT INTO flights "
        "(id, origin, destination, date, depart, time_of_day, price, seats_left) VALUES"
    )
    flight_rows = []
    for row in flights:
        flight_id, origin, dest, date, depart, tod, price, seats = row
        flight_rows.append(
            "  ("
            f"{sql_str(flight_id)}, {sql_str(origin)}, {sql_str(dest)}, {sql_str(date)}, "
            f"{sql_str(depart)}, {sql_str(tod)}, {price}, {seats})"
        )
    lines.append(",\n".join(flight_rows) + ";")
    lines.append("")
    lines.append("INSERT INTO reservations (flight_id, passenger_name, status) VALUES")
    res_rows = [
        f"  ({sql_str(flight_id)}, {sql_str(name)}, 'confirmed')"
        for flight_id, name in reservations
    ]
    lines.append(",\n".join(res_rows) + ";")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    rng = random.Random(0)
    flights = [list(row) for row in build_flights(rng)]
    reservations = build_reservations(rng, flights)
    if len(flights) != TARGET_FLIGHTS:
        raise SystemExit(f"expected {TARGET_FLIGHTS} flights, got {len(flights)}")
    if not any(row[0] == "UA100" and row[7] > 0 for row in flights):
        raise SystemExit("UA100 must have seats left")
    SEED_PATH.write_text(render_sql([tuple(row) for row in flights], reservations), encoding="utf-8")
    sold_out = sum(1 for row in flights if row[7] == 0)
    print(SEED_PATH)
    print("flights", len(flights))
    print("reservations", len(reservations))
    print("sold_out_flights", sold_out)


if __name__ == "__main__":
    main()
